name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

       - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.60.180.108
          username: linuxserver.io
          password: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: whoami